# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/sim/xsim_peripheral_led_tb/MIPS_System_LED_sim/MIPS_System_LED_sim.cache/wt [current_project]
set_property parent.project_path C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/sim/xsim_peripheral_led_tb/MIPS_System_LED_sim/MIPS_System_LED_sim.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/2024_CA_LAB/LAB/Final_Project_team1/hardware/sim/xsim_peripheral_led_tb/MIPS_System_LED_sim/MIPS_System_LED_sim.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/sim/xsim_peripheral_led_tb/mem_path.vh
read_mem C:/2024_CA_LAB/LAB/Final_Project_team1/software/01.led/code.hex
read_verilog -library xil_defaultlib {
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/ASYNC_RAM_DP.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/EXE_MEM_pipe_reg.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/GPIO.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/ID_EXE_pipe_reg.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/IF_ID_pipe_reg.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/MEM_WB_pipe_reg.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/MIPS_System.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/MIPS_cpu.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/SEG7_LUT.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/alu_32bit.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/clock_divider.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/control_unit.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/full_adder.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/hazard_unit.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/next_pc_logic_pipe.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/reg_file_async.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/ripple_carry_adder.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/seg7driver.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/sign_extension.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/write_back_address.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/src/rtl/write_back_data.v
  C:/2024_CA_LAB/LAB/Final_Project_team1/hardware/testbench/peripheral_tests_tb.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top peripheral_tests_tb -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef peripheral_tests_tb.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file peripheral_tests_tb_utilization_synth.rpt -pb peripheral_tests_tb_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
